GccTestablet/haussmann-medias-main

app/config/migrations/2023/Version20231005081307.php
app/src/Entity/Contract.php
app/src/Entity/Work.php
app/src/Form/Dto/Work/WorkFormDto.php

Fix: Change contract foreign keys to not null

---

app/config/migrations/2023/Version20231005112757.php
app/src/Controller/Company/CompanyContractController.php
app/src/Controller/Company/CompanyWorkController.php
app/src/Controller/Security/ProfileController.php
app/src/Entity/Company.php
app/src/Entity/User.php
app/src/Entity/Work.php
app/src/Repository/CompanyRepository.php
app/src/Repository/WorkRepository.php
app/src/Security/Voter/CompanyVoter.php
app/src/Service/Company/CompanyManager.php
app/src/Service/Company/CompanyUserAccessManager.php
app/src/Service/User/UserUpdater.php
app/src/Service/Work/WorkManager.php
app/src/Twig/Component/Layout/UserCompanySelectorComponent.php
app/templates/component/layout/user_company_selector.html.twig
app/templates/contract/index.html.twig
app/templates/shared/layout/_embedded/_navbar/_search.html.twig
app/templates/shared/layout/_embedded/_sidebar.html.twig
app/templates/work/show.html.twig
app/translations/beneficiary.fr.yaml
app/translations/company.fr.yaml
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml
app/translations/user.fr.yaml
app/translations/work.fr.yaml

Feature: User company selector

---

app/config/migrations/2023/Version20231006085001.php
app/src/Controller/Work/WorkAdaptationController.php
app/src/Controller/Work/WorkController.php
app/src/Entity/Beneficiary.php
app/src/Entity/BroadcastChannel.php
app/src/Entity/Contract.php
app/src/Entity/User.php
app/src/Entity/UserCompany.php
app/src/Entity/Work.php
app/src/Entity/WorkAdaptation.php
app/src/Form/Dto/Work/WorkAdaptationFormDto.php
app/src/Form/DtoFactory/Work/WorkAdaptationFormDtoFactory.php
app/src/Form/Handler/Work/WorkAdaptationFormHandler.php
app/src/Form/Type/Work/WorkAdaptationFormType.php
app/templates/work/adaptation/show.html.twig
app/templates/work/show.html.twig
app/translations/work.fr.yaml

Feature: Work adaptation

---

app/config/migrations/2023/Version20231006122958.php
app/config/migrations/2023/Version20231006143142.php
app/src/Controller/Work/WorkRevenueController.php
app/src/Entity/Work.php
app/src/Entity/WorkRevenue.php
app/src/Form/Dto/Work/WorkRevenueFormDto.php
app/src/Form/Dto/Work/WorkReversionFormDto.php
app/src/Form/DtoFactory/Work/WorkRevenueFormDtoFactory.php
app/src/Form/Handler/Work/WorkRevenueFormHandler.php
app/src/Form/Type/Work/WorkRevenueFormType.php
app/templates/work/adaptation/_embedded/_list.html.twig
app/templates/work/revenue/_embedded/_list.html.twig
app/templates/work/revenue/show.html.twig
app/templates/work/reversion/_embedded/_list.html.twig
app/templates/work/reversion/show.html.twig
app/templates/work/show.html.twig

Feature: Work revenue

---

docker-sync.yml
docker/docker-compose.dev.local.yaml

Fix: Docker sync path conflicts

---

app/src/Entity/Contract.php
app/src/Repository/ContractRepository.php
app/src/Repository/WorkRepository.php
app/src/Service/Contract/ContractManager.php
app/src/Service/Work/WorkManager.php

Feature: Paginator work and contract

---

app/src/Controller/Security/ProfileController.php
app/src/Form/Type/Work/WorkAdaptationFormType.php
app/templates/broadcast/channel/index.html.twig
app/templates/company/index.html.twig
app/templates/company/show.html.twig
app/templates/contract/_embedded/_list.html.twig
app/templates/contract/index.html.twig
app/templates/contract/show.html.twig
app/templates/shared/common/save.html.twig
app/templates/shared/layout/_embedded/_navbar/_user.html.twig
app/templates/shared/layout/_embedded/_sidebar.html.twig
app/templates/user/index.html.twig
app/templates/user/show.html.twig
app/templates/work/_embedded/_list.html.twig
app/templates/work/adaptation/_embedded/_list.html.twig
app/templates/work/adaptation/show.html.twig
app/templates/work/revenue/_embedded/_list.html.twig
app/templates/work/reversion/_embedded/_list.html.twig
app/templates/work/show.html.twig
app/translations/company.fr.yaml
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml
app/translations/security.fr.yaml
app/translations/user.fr.yaml
app/translations/work.fr.yaml

Translations

---

app/src/Form/Dto/Work/WorkFormDto.php
app/src/Form/Type/Work/WorkFormType.php
app/templates/company/show.html.twig
app/templates/user/index.html.twig
app/templates/user/show.html.twig
app/templates/work/show.html.twig
app/translations/user.fr.yaml
app/translations/work.fr.yaml

More translations added

---

app/src/Controller/Work/WorkAdaptationController.php
app/src/Controller/Work/WorkRevenueController.php
app/src/Controller/Work/WorkReversionController.php
app/templates/shared/common/remove.html.twig
app/templates/work/adaptation/_embedded/_list.html.twig
app/templates/work/revenue/_embedded/_list.html.twig
app/templates/work/reversion/_embedded/_list.html.twig
app/translations/misc.fr.yaml
app/translations/work.fr.yaml

Feature: Work adaptation, reversion and revenue removal

---

app/src/Form/Validator/UniqueEntityFieldValidator.php

Fix: Unique entity constraint

---

app/assets/controllers.json
app/config/migrations/2023/Version20231010083159.php
app/src/Controller/Setting/TerritoryController.php
app/src/Entity/Contract.php
app/src/Entity/Territory.php
app/src/Form/Dto/Company/CompanyContractFormDto.php
app/src/Form/Dto/Setting/TerritoryFormDto.php
app/src/Form/DtoFactory/Setting/TerritoryFormDtoFactory.php
app/src/Form/Handler/Setting/TerritoryFormHandler.php
app/src/Form/Type/Common/TerritoryAutocompleteField.php
app/src/Form/Type/Company/CompanyContractFormType.php
app/src/Form/Type/Setting/TerritoryFormType.php
app/src/Service/Setting/TerritoryManager.php
app/templates/contract/show.html.twig
app/templates/setting/territory/index.html.twig
app/templates/setting/territory/show.html.twig
app/templates/shared/layout/_embedded/_sidebar.html.twig
app/translations/contract.fr.yaml
app/translations/setting.fr.yaml

Fixture: Territories

---

app/config/migrations/2023/Version20231010102048.php
app/src/Entity/BroadcastChannel.php
app/src/Entity/Work.php
app/src/Form/Dto/Work/WorkFormDto.php
app/src/Form/DtoFactory/Work/WorkFormDtoFactory.php
app/src/Form/Type/Common/BroadcastChannelAutocompleteField.php
app/src/Form/Type/Work/WorkFormType.php
app/src/Form/Type/Work/WorkReversionFormType.php
app/src/Repository/Broadcast/BroadcastChannelRepository.php
app/src/Repository/WorkRepository.php
app/src/Service/Work/WorkManager.php
app/src/Twig/Extension/FormatExtension.php
app/src/Twig/Runtime/FormatExtensionRuntime.php
app/templates/work/show.html.twig
app/translations/work.fr.yaml

Changes: Work and adaptation

---

app/composer.json
app/composer.lock
app/src/Controller/Company/CompanyDistributionContractController.php
app/src/Controller/Contract/DistributionContractController.php
app/src/Controller/Setting/BroadcastChannelController.php
app/src/Entity/AcquisitionContract.php
app/src/Enum/Common/FrequencyEnum.php
app/src/Repository/Contract/AcquisitionContractRepository.php
app/src/Repository/WorkRepository.php
app/src/Service/Contract/ContractManager.php
app/src/Service/Contract/DistributionContractTemplateGenerator.php
app/src/Service/Setting/BroadcastChannelManager.php
app/src/Service/Work/WorkManager.php
app/src/Tools/Manager/UploadFileManager.php
app/src/Tools/Parser/CsvParser.php
app/templates/distribution_contract/show.html.twig
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml

Feature: Distribution contract CSV template export

---

app/src/Controller/Company/CompanyAcquisitionContractController.php
app/src/Form/Dto/Contract/AcquisitionContractFormDto.php
app/src/Form/Dto/Work/WorkFormDto.php
app/src/Form/DtoFactory/Contract/AcquisitionContractFormDtoFactory.php
app/src/Form/Handler/Contract/AcquisitionContractFormHandler.php
app/src/Form/Type/Contract/AcquisitionContractFormType.php
app/src/Form/Type/Work/WorkFormType.php

Changes: Acquisition contract moved in contract folder

---

app/src/Controller/Work/WorkTerritoryController.php
app/src/Entity/Work/Work.php
app/src/Entity/Work/WorkTerritory.php
app/src/Form/Dto/Work/WorkTerritoryFormDto.php
app/src/Form/DtoFactory/Work/WorkTerritoryFormDtoFactory.php
app/src/Form/Handler/Work/WorkTerritoryFormHandler.php
app/src/Form/Type/Work/WorkTerritoryFormType.php
app/src/Service/Work/WorkTerritoryManager.php
app/src/Tools/Parser/ArrayParser.php
app/src/Twig/Extension/CoreExtension.php
app/src/Twig/Runtime/CoreExtensionRuntime.php
app/templates/work/show.html.twig
app/templates/work/territory/_embedded/_list.html.twig
app/templates/work/territory/manage.html.twig

Feature: Work territory manager

---

app/composer.json
app/composer.lock
app/config/migrations/2023/Version20231018084133.php
app/src/Controller/Company/CompanyDistributionContractController.php
app/src/Controller/Contract/DistributionContractFileController.php
app/src/Entity/Contract/DistributionContract.php
app/src/Entity/Contract/DistributionContractFile.php
app/src/Form/Dto/Contract/DistributionContractFormDto.php
app/src/Form/DtoFactory/Contract/DistributionContractFormDtoFactory.php
app/src/Form/Handler/Contract/DistributionContractFormHandler.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Service/Contract/DistributionContractFileHelper.php
app/src/Tools/Parser/HTMLDomParser.php
app/templates/distribution_contract/_embedded/_list.html.twig
app/templates/distribution_contract/show.html.twig
app/translations/contract.fr.yaml

Feature: Distribution contract multiple files

---

app/config/migrations/2023/Version20231018111024.php
app/src/Controller/Contract/DistributionContractWorkController.php
app/src/Entity/Contract/DistributionContract.php
app/src/Entity/Contract/DistributionContractWork.php
app/src/Form/Dto/Contract/DistributionContractFormDto.php
app/src/Form/Dto/Contract/DistributionContractWorkFormDto.php
app/src/Form/Dto/Contract/DistributionContractWorkRevenueImportFormDto.php
app/src/Form/DtoFactory/Contract/DistributionContractFormDtoFactory.php
app/src/Form/DtoFactory/Contract/DistributionContractWorkFormDtoFactory.php
app/src/Form/Handler/Contract/DistributionContractWorkFormHandler.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Form/Type/Contract/DistributionContractWorkFormType.php
app/src/Repository/WorkRepository.php
app/templates/distribution_contract/_embedded/_list.html.twig
app/templates/distribution_contract/show.html.twig

Feature: Distribution contract work form

---

app/composer.json
app/composer.lock
app/config/bundles.php
app/config/services_test.yaml
app/rector.php
app/src/Tools/CastTool.php
app/src/Tools/Parser/ArrayParser.php
app/src/Tools/Parser/ObjectParser.php
app/symfony.lock
app/tests/Fixtures/Doctrine/CompanyFixture.php
app/tests/Fixtures/Doctrine/Setting/AdaptationCostTypeFixture.php
app/tests/Fixtures/Doctrine/Setting/BroadcastChannelFixture.php
app/tests/Fixtures/Doctrine/Setting/BroadcastServiceFixture.php
app/tests/Fixtures/Doctrine/Setting/TerritoryFixture.php
app/tests/Fixtures/Doctrine/Shared/AbstractFixture.php
app/tests/Fixtures/Doctrine/UserCompanyFixture.php
app/tests/Fixtures/Doctrine/UserFixture.php
app/tests/Unit/Tools/Parser/ArrayParserTest.php

Tests: Fixtures added

---

app/.env.test
app/config/packages/doctrine.yaml
app/config/services_test.yaml
app/tests/AbstractTestCase.php
app/tests/Integration/Service/User/UserManagerTest.php
app/tests/Tools/Loader/DoctrineFixtureLoader.php
app/tests/bootstrap.php

Tests: Fixtures loader added

---

app/config/services_test.yaml
app/src/EventSubscriber/UserEventSubscriber.php
app/src/Security/LoginFormAuthenticator.php
app/src/Service/User/UserActivityManager.php
app/tests/AbstractTestCase.php
app/tests/Fixtures/Doctrine/UserFixture.php
app/tests/Integration/Service/Security/SecurityManagerTest.php
app/tests/Integration/Service/Security/UserPasswordManagerTest.php
app/tests/Integration/Service/User/UserActivityManagerTest.php
app/tests/Integration/Service/User/UserManagerTest.php
app/tests/Integration/Service/User/UserUpdaterTest.php
app/tests/Tools/Loader/DoctrineFixtureLoader.php
app/tests/Unit/EventSubscriber/UserEventSubscriberTest.php
app/tests/Unit/Service/Security/UserActivityManagerTest.php

Tests: Security tests added

---

app/config/services_test.yaml
app/tests/Fixtures/Doctrine/Setting/BroadcastChannelFixture.php
app/tests/Integration/Service/Company/CompanyManagerTest.php
app/tests/Integration/Service/Company/CompanyUserAccessManagerTest.php
app/tests/Integration/Service/Company/CompanyUserManagerTest.php
app/tests/Integration/Service/Setting/AdaptationCostTypeManagerTest.php
app/tests/Integration/Service/Setting/BroadcastChannelManagerTest.php
app/tests/Integration/Service/Setting/TerritoryManagerTest.php

Tests: Company and Setting tests added

---

app/tests/Fixtures/Doctrine/Contract/DistributionContractFileFixture.php
app/tests/Fixtures/Doctrine/Contract/DistributionContractFixture.php
app/tests/Fixtures/Doctrine/Contract/DistributionContractWorkFixture.php
app/tests/Fixtures/Doctrine/Contract/DistributionContractWorkRevenueFixture.php
app/tests/Fixtures/Doctrine/Contract/DistributionContractWorkTerritoryFixture.php

Tests: Distribution contract fixtures added

---

app/assets/js/controllers/datatable/table_expand_controller.ts
app/assets/scss/custom/_main.scss
app/assets/scss/oneui/_variables.scss
app/templates/acquisition_contract/_embedded/_information.html.twig
app/templates/acquisition_contract/show.html.twig
app/templates/company/show.html.twig
app/templates/shared/layout/layout_base.html.twig
app/templates/work/_embedded/_information.html.twig
app/templates/work/_embedded/_list.html.twig
app/templates/work/show.html.twig
app/translations/contract.fr.yaml
app/translations/work.fr.yaml

Design: Contract and work design updated

---

app/config/migrations/2023/Version20231023075342.php
app/src/Controller/Company/CompanyDistributionContractController.php
app/src/Controller/Contract/DistributionContractController.php
app/src/Controller/Contract/DistributionContractWorkTerritoryController.php
app/src/Entity/Contract/DistributionContract.php
app/src/Form/Dto/Contract/DistributionContractFormDto.php
app/src/Form/DtoFactory/Contract/DistributionContractWorkTerritoryFormDtoFactory.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Service/Contract/DistributionContractFileHelper.php
app/src/Service/Contract/DistributionContractWorkRevenueImporter.php
app/src/Tools/Parser/CsvParser.php
app/src/Tools/Parser/HTMLDomParser.php
app/templates/distribution_contract/_embedded/_information.html.twig
app/templates/distribution_contract/show.html.twig
app/templates/distribution_contract/work/territory/manage.html.twig
app/translations/contract.fr.yaml

Changes: Distribution contract form changes

---

app/config/migrations/2023/Version20231023132159.php
app/src/Entity/Work/WorkAdaptation.php
app/src/Form/Dto/Work/WorkAdaptationFormDto.php
app/src/Form/Type/Work/WorkAdaptationFormType.php
app/templates/work/adaptation/_embedded/_list.html.twig

Please enter the commit message for your changes. Lines starting
Add a free field comment to work adaptation form

Ajout comment in work adaptation

---

app/config/migrations/2023/Version20231023092658.php
app/config/migrations/2023/Version20231023142402.php
app/src/Controller/Company/CompanyAcquisitionContractController.php
app/src/Controller/Contract/AcquisitionContractController.php
app/src/Controller/Contract/AcquisitionContractFileController.php
app/src/Entity/Contract/AcquisitionContract.php
app/src/Entity/Contract/AcquisitionContractFile.php
app/src/Entity/Contract/DistributionContractFile.php
app/src/Form/Dto/Contract/AcquisitionContractFormDto.php
app/src/Form/DtoFactory/Contract/AcquisitionContractFormDtoFactory.php
app/src/Form/Handler/Contract/AcquisitionContractFormHandler.php
app/src/Form/Type/Contract/AcquisitionContractFormType.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Service/Contract/ContractFileHelper.php
app/src/Tools/Manager/UploadFileManager.php
app/templates/acquisition_contract/_embedded/_information.html.twig
app/templates/acquisition_contract/_embedded/_list.html.twig
app/templates/acquisition_contract/show.html.twig
app/templates/work/_embedded/_list.html.twig

Changes: Acquisition contract multiple files and form changes

---

app/src/Entity/Contract/DistributionContractWork.php
app/src/Entity/Work/Work.php
app/templates/work/_distribution_contract_list.html.twig
app/templates/work/show.html.twig

Changes: Work distribution contract tab

---

app/config/migrations/2023/Version20231024085402.php
app/src/Entity/Work/Work.php
app/src/Form/Dto/Work/WorkFormDto.php
app/src/Form/Type/Work/WorkFormType.php

Feature add currency work form

---

app/src/Controller/Security/ProfileController.php
app/src/Form/Dto/Contract/AcquisitionContractFormDto.php
app/src/Form/Type/Contract/AcquisitionContractFormType.php
app/templates/component/layout/user_company_selector.html.twig
app/tests/End2End/Contract/AcquisitionContract/CreatePageTest.php
app/tests/End2End/Contract/AcquisitionContract/IndexPageTest.php
app/tests/End2End/Shared/AbstractEnd2EndTestCase.php
app/tests/End2End/Shared/Traits/AssertActionTrait.php
app/tests/End2End/Shared/Traits/InteractionActionTrait.php
app/tests/End2End/Shared/Traits/UserTrait.php
app/translations/contract.fr.yaml

Tests: Acquisition contract creation page End2End

---

app/src/Controller/Contract/DistributionContractController.php
app/src/Controller/Security/ProfileController.php
app/src/Form/Dto/Contract/DistributionContractFormDto.php
app/src/Form/DtoFactory/Contract/AcquisitionContractFormDtoFactory.php
app/src/Form/DtoFactory/Contract/DistributionContractFormDtoFactory.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/templates/distribution_contract/index.html.twig
app/templates/shared/layout/_embedded/_sidebar.html.twig
app/templates/shared/layout/layout_base.html.twig
app/tests/End2End/Contract/AcquisitionContract/CreatePageTest.php
app/tests/End2End/Contract/DistributionContract/CreatePageTest.php
app/tests/End2End/Contract/DistributionContract/IndexPageTest.php
app/tests/End2End/Layout/MenuRedirectionTest.php
app/tests/Fixtures/Doctrine/CompanyFixture.php
app/tests/Fixtures/Doctrine/Contract/DistributionContractFixture.php
app/translations/contract.fr.yaml

Tests distribution contract end2end tests added

---

app/assets/js/controllers/datatable/table_expand_controller.ts
app/src/Controller/Contract/AcquisitionContractController.php
app/src/Controller/Security/ProfileController.php
app/src/Controller/Work/WorkController.php
app/templates/distribution_contract/_embedded/_work_list.html.twig
app/templates/shared/layout/_embedded/_sidebar.html.twig
app/templates/work/_embedded/_list.html.twig
app/templates/work/territory/_embedded/_list.html.twig
app/tests/End2End/Contract/AcquisitionContract/IndexPageTest.php
app/tests/End2End/Contract/AcquisitionContract/ShowPageTest.php
app/tests/End2End/Contract/AcquisitionContract/UpdatePageTest.php
app/tests/End2End/Contract/DistributionContract/ShowPageTest.php
app/tests/End2End/Contract/DistributionContract/UpdatePageTest.php
app/tests/End2End/Layout/MenuRedirectionTest.php
app/tests/End2End/Shared/Traits/AssertTableTrait.php
app/tests/Fixtures/Doctrine/Contract/AcquisitionContractFixture.php
app/tests/Tools/Loader/DoctrineFixtureLoader.php

Tests: Contract show and update pages end2end tests added

---

app/assets/js/controllers/form/reset_controller.ts
app/src/Enum/Pager/ColumnEnum.php
app/src/Form/Dto/Work/WorkFormDto.php
app/src/Form/Type/Pager/Shared/BasePagerFormType.php
app/src/Form/Type/Pager/Work/WorkPagerFormType.php
app/src/Pager/PagerManager.php
app/src/Pager/RequestTransformer/AbstractRequestTransformer.php
app/src/Pager/RequestTransformer/KnpPaginatorRequestTransformer.php
app/src/Pager/Shared/AbstractPager.php
app/src/Pager/Shared/PagerInterface.php
app/src/Pager/Work/WorkPager.php
app/src/Repository/WorkRepository.php
app/templates/component/common/data_table/data_table.html.twig
app/templates/work/index.html.twig
app/translations/misc.fr.yaml
app/translations/work.fr.yaml

Feature: Work pager filters

---

app/assets/js/controllers/widgets/date_range_picker_controller.ts
app/package.json
app/src/Controller/Contract/AcquisitionContractController.php
app/src/Enum/Pager/ColumnEnum.php
app/src/Form/Dto/Common/DateRangeFormDto.php
app/src/Form/Transformer/DateRangeTypeTransformer.php
app/src/Form/Type/Common/CompanyEntityField.php
app/src/Form/Type/Common/WorkEntityField.php
app/src/Form/Type/Pager/Contract/AcquisitionContractPagerFormType.php
app/src/Form/Type/Pager/Work/WorkPagerFormType.php
app/src/Form/Type/Shared/DateRangeType.php
app/src/Pager/Contract/AcquisitionContractPager.php
app/src/Pager/RequestTransformer/KnpPaginatorRequestTransformer.php
app/src/Pager/Work/WorkPager.php
app/src/Repository/Contract/AcquisitionContractRepository.php
app/src/Repository/WorkRepository.php
app/src/Tools/Parser/DateParser.php
app/templates/acquisition_contract/index.html.twig
app/templates/work/index.html.twig
app/tests/Unit/Tools/Parser/DateParserTest.php
app/translations/contract.fr.yaml
app/yarn.lock

Feature: Acquisition contract pager and filters

---

app/src/Controller/Contract/DistributionContractController.php
app/src/Entity/Contract/DistributionContract.php
app/src/Enum/Pager/ColumnEnum.php
app/src/Form/Type/Pager/Contract/DistributionContractPagerFormType.php
app/src/Pager/Contract/DistributionContractPager.php
app/src/Repository/Contract/AcquisitionContractRepository.php
app/src/Repository/Contract/DistributionContractRepository.php
app/templates/distribution_contract/index.html.twig
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml

Feature: Distribution contract pager

---

app/config/migrations/2023/Version20231030140138.php
app/src/Controller/Work/WorkController.php
app/src/Entity/Contract/AcquisitionContract.php
app/src/Entity/Contract/AcquisitionContractFile.php
app/src/Entity/Contract/DistributionContractFile.php
app/src/Entity/Shared/FileInterface.php
app/src/Enum/Common/FrequencyEnum.php
app/src/Form/Dto/Contract/AcquisitionContractFormDto.php
app/src/Form/DtoFactory/Contract/AcquisitionContractFormDtoFactory.php
app/src/Form/DtoFactory/Contract/DistributionContractFormDtoFactory.php
app/src/Form/Handler/Contract/AcquisitionContractFormHandler.php
app/src/Form/Handler/Contract/DistributionContractFormHandler.php
app/src/Form/Type/Contract/AcquisitionContractFormType.php
app/src/Repository/Contract/AcquisitionContractRepository.php
app/src/Twig/Component/Layout/SearchBarComponent.php
app/templates/acquisition_contract/_embedded/_information.html.twig
app/templates/work/show.html.twig
app/templates/work/tab/distribution_contracts.html.twig
app/templates/work/tab/distribution_costs.html.twig
app/templates/work/tab/reversions.html.twig
app/templates/work/tab/territories.html.twig
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml

Feature: Work tabs and report frequency comment added

---

app/config/migrations/2023/Version20231030154838.php
app/src/Controller/Work/WorkAdaptationController.php
app/src/Controller/Work/WorkReversionController.php
app/src/Controller/Work/WorkTerritoryController.php
app/src/Entity/Contract/DistributionContractWorkTerritory.php
app/src/Entity/Work/WorkTerritory.php
app/src/Form/Dto/Work/WorkReversionFormDto.php
app/src/Form/Dto/Work/WorkTerritoryFormDto.php
app/src/Form/DtoFactory/Work/WorkTerritoryFormDtoFactory.php
app/src/Form/Handler/Work/WorkTerritoryFormHandler.php
app/src/Form/Type/Work/WorkTerritoryFormType.php
app/src/Pager/Contract/DistributionContractWorkPager.php
app/src/Pager/Work/WorkPager.php
app/src/Twig/Extension/FormatExtension.php
app/src/Twig/Runtime/FormatExtensionRuntime.php
app/templates/work/territory/_embedded/_list.html.twig
app/templates/work/territory/manage.html.twig
app/translations/misc.fr.yaml
app/translations/work.fr.yaml

Feature: Work territory exclusive

---

app/config/migrations/2023/Version20231031160824.php
app/src/Entity/Work/Work.php
app/src/Form/Type/Work/WorkFormType.php

Changes: Work unique constraint removed

---

app/assets/js/controllers/datatable/fill_all_controller.ts
app/src/Controller/Work/WorkReversionController.php
app/src/Entity/Setting/AdaptationCostType.php
app/src/Entity/Work/Work.php
app/src/Entity/Work/WorkReversion.php
app/src/Enum/Pager/ColumnEnum.php
app/src/Form/Dto/Work/WorkReversionFormDto.php
app/src/Form/DtoFactory/Work/WorkReversionFormDtoFactory.php
app/src/Form/Handler/Work/WorkReversionFormHandler.php
app/src/Form/Type/Common/AdaptationCostTypeEntityField.php
app/src/Form/Type/Common/BroadcastChannelEntityField.php
app/src/Form/Type/Common/TerritoryEntityField.php
app/src/Form/Type/Common/WorkEntityField.php
app/src/Form/Type/Work/WorkAdaptationFormType.php
app/src/Form/Type/Work/WorkFormType.php
app/src/Form/Type/Work/WorkReversionFormType.php
app/src/Pager/Work/WorkPager.php
app/src/Pager/Work/WorkReversionPager.php
app/src/Repository/Broadcast/BroadcastChannelRepository.php
app/src/Repository/Contract/AcquisitionContractRepository.php
app/src/Repository/Contract/DistributionContractRepository.php
app/src/Repository/Setting/AdaptationCostTypeRepository.php
app/src/Repository/Setting/TerritoryRepository.php
app/src/Repository/WorkRepository.php
app/src/Service/Work/WorkReversionManager.php
app/templates/work/reversion/manage.html.twig
app/templates/work/tab/reversions.html.twig
app/translations/misc.fr.yaml

Changes: Work reversions form updated

---

app/src/Controller/Work/WorkTerritoryController.php
app/src/Entity/Work/Work.php
app/src/Enum/Pager/ColumnEnum.php
app/src/Form/DtoFactory/Work/WorkTerritoryFormDtoFactory.php
app/src/Form/Type/Common/BroadcastChannelEntityField.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Pager/Work/WorkTerritoryPager.php
app/src/Repository/Broadcast/BroadcastChannelRepository.php
app/src/Repository/Work/WorkTerritoryRepository.php
app/src/Service/Setting/BroadcastChannelManager.php
app/src/Service/Setting/TerritoryManager.php
app/src/Tools/Parser/ArrayCollectionParser.php
app/src/Twig/Extension/FormatExtension.php
app/src/Twig/Runtime/FormatExtensionRuntime.php
app/templates/work/reversion/manage.html.twig
app/templates/work/territory/manage.html.twig
app/translations/work.fr.yaml

Changes: More archived restrictions

---

app/config/migrations/2023/Version20231102141752.php
app/config/packages/twig.yaml
app/src/Entity/Contract/DistributionContract.php
app/src/Entity/Contract/DistributionContractWork.php
app/src/Entity/Contract/DistributionContractWorkTerritory.php
app/src/Form/Dto/Contract/DistributionContractFormDto.php
app/src/Form/DtoFactory/Contract/DistributionContractWorkTerritoryFormDtoFactory.php
app/src/Form/Handler/Contract/DistributionContractWorkFormHandler.php
app/src/Form/Type/Common/TerritoryEntityField.php
app/src/Form/Type/Contract/DistributionContractFormType.php
app/src/Form/Type/Pager/Contract/DistributionContractWorkPagerFormType.php
app/src/Repository/Contract/DistributionContractWorkRepository.php
app/src/Service/Contract/DistributionContractWorkTerritoryManager.php
app/src/Tools/Parser/ArrayCollectionParser.php
app/templates/distribution_contract/_embedded/_information.html.twig
app/templates/distribution_contract/work/territory/manage.html.twig
app/templates/shared/layout/_embedded/_navbar.html.twig
app/tests/End2End/Contract/DistributionContract/IndexPageTest.php
app/translations/misc.fr.yaml

Feature: Distribution contract work, add territory automatically

---

app/src/Enum/Pager/ColumnEnum.php
app/src/Form/Type/Pager/Work/WorkPagerFormType.php
app/src/Repository/WorkRepository.php
app/src/Service/Contract/DistributionContractWorkTerritoryManager.php
app/templates/work/index.html.twig
app/translations/contract.fr.yaml
app/translations/misc.fr.yaml

Changes: Work pager territory filters added

---

app/src/Form/DtoFactory/Contract/DistributionContractFormDtoFactory.php
app/src/Tools/Manager/UploadFileManager.php
app/templates/distribution_contract/work/territory/manage.html.twig
app/translations/misc.fr.yaml

Changes: Distribution contract work territory not acquired message

---

app/src/Controller/Work/WorkAdaptationController.php
app/src/Form/Dto/Work/WorkTerritoryFormDto.php
app/templates/distribution_contract/work/territory/manage.html.twig
app/templates/work/territory/manage.html.twig
app/tests/Behat/Traits/DataTableTrait.php
app/tests/Behat/features/contract/distributionContract/show.feature
app/tests/Behat/features/work/adaptationCost/create.feature
app/tests/Behat/features/work/adaptationCost/update.feature
app/tests/Behat/features/work/reversion/manage.feature
app/tests/Behat/features/work/show.feature
app/tests/Behat/features/work/territory/manage.feature

Tests: Work territories, reversions and cost end2end tests added
